version: 1.0.{build}
configuration: Release
platform:
- x86
- x64
build:
  verbosity: minimal
after_build:
- cmd: IF "%PLATFORM%"=="x64" ( C:\projects\lfstack\lfstack_vs\%PLATFORM%\Release\lfstack_vs.exe ) ELSE ( C:\projects\lfstack\lfstack_vs\Release\lfstack_vs.exe )